#!/bin/bash

COMMIT=`git describe --long`
DATE=`date`

cat << EOF > src/git_config.h
// Autogenerated header file

#ifndef GIT_CONFIG_H
#define GIT_CONFIG_H

#define GIT_COMMIT "$COMMIT"

#define BUILD_DATETIME "$DATE"

#define BUILD_USERNAME "$USERNAME$USER"

#endif // GIT_CONFIG_H

EOF
